#!/bin/bash
#  a script that factorize as many numbers as possible
# into a product of two smaller numbers.

file_name=$1


function getFactor
{
  number=$1
    for (( i=2; i<=(number / 2); i++ ));
      do
        if [[ $(expr "$number" % "$i") -eq "0" ]]; then
          num2=$((number / i))
          echo "$number=$num2*$i"
          break
        fi
      done
}

while IFS= read -r line;
do
    getFactor "$line"
done < "$file_name"
