#!/usr/bin/python3

# a script that factorize as many numbers as possible
# into a product of two smaller numbers.

import math
from sys import argv


def print_factors(value):
    number_sqrt = math.sqrt(value)
    number_sqrt_int = int(number_sqrt)
    if number_sqrt == number_sqrt_int:
        print("{}={}*{}".format(value, value // number_sqrt_int,
              number_sqrt_int))
        return

    if value % 2 == 0:
        print("{}={}*{}".format(value, value // 2, 2))
        return

    if value % 3 == 0:
        print("{}={}*{}".format(value, value // 3, 3))
        return

    if value % 5 == 0:
        print("{}={}*{}".format(value, value // 5, 5))
        return

    if value % 7 == 0:
        print("{}={}*{}".format(value, value // 7, 7))
        return

    if value % 11 == 0:
        print("{}={}*{}".format(value, value // 11, 11))
        return

    if value % 13 == 0:
        print("{}={}*{}".format(value, value // 13, 13))
        return

    if value % 17 == 0:
        print("{}={}*{}".format(value, value // 17, 17))
        return

    if value % 19 == 0:
        print("{}={}*{}".format(value, value // 19, 19))
        return

    if value % 23 == 0:
        print("{}={}*{}".format(value, value // 23, 23))
        return

    if value % 29 == 0:
        print("{}={}*{}".format(value, value // 29, 29))
        return

    for i in range(31, number_sqrt_int):
        if value % i == 0:
            print("{}={}*{}".format(value, value // i, i))
            break


def main():
    if len(argv) != 2:
        exit()

    try:
        with open(argv[1]) as file:
            for line in file.readlines():
                value = int(line.split('\n')[0])
                print_factors(value)
    except Exception as e:
        print(e)
        pass


if __name__ == "__main__":
    main()
