#!/usr/bin/python3

# a script that factorize as many numbers as possible
# into a product of two smaller numbers.

import math
from sys import argv


def print_factors(value):
    number_sqrt = int(math.sqrt(value))
    for i in range(2, number_sqrt):
        if value % i == 0:
            print("{}={}*{}".format(value, value // i, i))
            break


def main():
    if len(argv) != 2:
        exit()

    try:
        with open(argv[1]) as file:
            for line in file.readlines():
                value = int(line.split('\n')[0])
                print_factors(value)
    except Exception as e:
        print(e)
        pass


if __name__ == "__main__":
    main()

