#!/usr/bin/python3

# a script that factorize as many numbers as possible
# into a product of two prime numbers.

import math
from sys import argv


def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True


def print_factors(value):
    number_sqrt = math.sqrt(value)
    number_sqrt_int = int(number_sqrt)

    if value % 2 == 0 and is_prime(value // 2):
        print("{}={}*{}".format(value, value // 2, 2))
        return

    for i in range(3, number_sqrt_int, 2):
        if value % i == 0 and is_prime(value // i) and is_prime(i):
            print("{}={}*{}".format(value, value // i, i))
            break


def main():
    if len(argv) != 2:
        exit()

    try:
        with open(argv[1]) as file:
            for line in file.readlines():
                value = int(line.split('\n')[0])
                print_factors(value)
    except Exception as e:
        print(e)
        pass


if __name__ == "__main__":
    main()
